CREATE TABLE #TABLERESULT (
DatabaseName VARCHAR(MAX),
TableName VARCHAR(MAX)
)
INSERT INTO #TABLERESULT
EXEC master.sys.sp_MSforeachdb 
'USE [?]
SELECT 
DB_NAME() AS DatabaseName,
table_name as TableName
FROM INFORMATION_SCHEMA.TABLES
WHERE table_type = "BASE TABLE"
AND TABLE_NAME = "ent_auto_terc"'
GO
SELECT * FROM #TABLERESULT
GO
--DROP TABLE #TABLERESULT
