SELECT 'DELETE FROM ['+ TABLE_SCHEMA +'].['+ TABLE_NAME +']
GO'
FROM INFORMATION_SCHEMA.TABLES;



SELECT 'DELETE FROM ['+ TABLE_SCHEMA +'].['+ TABLE_NAME +']
GO'
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE';
